CREATE TABLE Review(
    userID CHAR(64) REFERENCES User(EMAIL) ON UPDATE CASCADE,
    gameID CHAR(64) REFERENCES Games(GameID) ON UPDATE CASCADE,
    review_text TEXT,   
    time_stamp DATE,
    rating DOUBLE,
    PRIMARY KEY(userID,gameID)
);

CREATE TABLE Likes(
    userID CHAR(64) REFERENCES User(EMAIL) ON UPDATE CASCADE,
    gameID CHAR(64) REFERENCES Games(GameID) ON UPDATE CASCADE, 
    timestamp DATETIME,
    PRIMARY KEY(userID,gameID)
);